// This file is automatically generated. Do not modify it manually.

package plugin

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.github.matterpoll.matterpoll",
	Version: "1.3.0",
}
