version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - hanzei
  assignees:
  - hanzei
  labels:
  - 3. To Review
