version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
  - "hanzei"
  assignees:
  - "hanzei"
  labels:
  - "3. To Review"
  allowed_updates:
    - match:
      update_type: "security"
