linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: true
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  govet:
    check-shadowing: true
  misspell:
    locale: US
  maligned:
    suggest-new: true
  
linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - maligned
    - misspell
    - scopelint
    - unconvert

issues:
  exclude-rules:
        # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - gocyclo
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
