version: "2"
run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - forbidigo
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    forbidigo:
      forbid:
        - pattern: '^.*\.MustLocalize.*(# MustLocalize may cause panic such as #252, use one of localize functions in utils package instead)?'
    goconst:
      min-len: 2
      min-occurrences: 2
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US

  exclusions:
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
        path: _test\.go

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/matterpoll/matterpoll
