[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~4.6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.1.0"
