name: cd
on:
  workflow_run:
    workflows: ["ci"]
    branches-ignore: ["*"]
    types:
      - completed
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  plugin-cd:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-cd.yml@86a78bd5bf6e009254bd0e23e316601d9d0db472
    secrets: inherit
