name: Check Mocks
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-mocks:
    name: Check Mocks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Check if mocks are up to date
        run: |
          # Run make mocks
          make mocks
          
          # Check if any files were changed
          git diff --exit-code
          
          # If git diff returns a non-zero exit code, it means files were changed
          if [ $? -ne 0 ]; then
            echo "::error::Running 'make mocks' changed files. Please run 'make mocks' locally and commit the changes."
            exit 1
          fi