name: Build Mattermost Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          make deps

      - name: Build plugin
        run: |
          make dist

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v2
        with:
          name: mattermost-plugin
          path: dist/*.tar.gz
